import type { Metadata } from "next";
import LegalPage from "../legal-page";

export const metadata: Metadata = {
  title: "Política de Privacidade | Wakilon Gestor",
  description: "Saiba como a Wakilon Gestor coleta, utiliza, armazena e protege dados pessoais em conformidade com a LGPD.",
  alternates: { canonical: "https://wakilongestor.com.br/privacidade/" },
};

export default function PrivacyPage() {
  return <LegalPage kicker="PRIVACIDADE E LGPD" title="Política de Privacidade" intro="Esta política explica de forma transparente como os dados pessoais podem ser tratados durante o uso do site e o contato com a Wakilon Gestor." sections={[
    { title: "Quem somos", content: <><p>A Wakilon Gestor presta serviços de marketing digital, gestão de tráfego, desenvolvimento de páginas, funis, rastreamento de dados e direção comercial para empresas e profissionais, com atuação especializada no segmento jurídico.</p><p>Para fins desta política, a Wakilon Gestor poderá atuar como controladora dos dados coletados diretamente em seus canais e como operadora quando tratar dados seguindo orientações de um cliente.</p></> },
    { title: "Dados que podem ser coletados", content: <><p>Podemos coletar dados fornecidos voluntariamente, como nome, e-mail, telefone, cargo, empresa, área de atuação, faixa de faturamento, respostas de formulários e conteúdo de mensagens.</p><p>Também podem ser registrados dados técnicos, como endereço IP, tipo de dispositivo, navegador, páginas acessadas, origem da visita, eventos de conversão e identificadores de cookies, quando essas tecnologias estiverem habilitadas.</p></> },
    { title: "Como utilizamos os dados", content: <><p>Os dados podem ser usados para responder contatos, realizar diagnóstico comercial, enviar propostas solicitadas, executar contratos, melhorar a experiência do site, medir campanhas, prevenir fraudes, cumprir obrigações legais e manter registros necessários à prestação dos serviços.</p><p>Comunicações de marketing somente serão enviadas quando houver base legal aplicável, e o titular poderá solicitar o cancelamento a qualquer momento.</p></> },
    { title: "Bases legais", content: <><p>O tratamento poderá se apoiar em consentimento, execução de contrato ou procedimentos preliminares, cumprimento de obrigação legal ou regulatória, exercício regular de direitos e legítimo interesse, sempre com avaliação de necessidade, finalidade e impacto aos titulares.</p></> },
    { title: "Cookies e tecnologias de medição", content: <><p>Cookies essenciais podem ser usados para funcionamento e segurança. Cookies analíticos e de publicidade poderão medir navegação, atribuir conversões e melhorar campanhas. Quando exigido, essas tecnologias dependerão de escolha válida do usuário.</p><p>O usuário pode ajustar cookies no navegador. A desativação de determinadas categorias pode limitar funções ou reduzir a precisão das medições.</p></> },
    { title: "Compartilhamento e operadores", content: <><p>Dados poderão ser processados por provedores necessários à operação, como hospedagem, e-mail, formulários, CRM, WhatsApp, análise, Meta, Google e TikTok. O compartilhamento é limitado ao necessário e sujeito às regras e medidas de segurança aplicáveis.</p><p>Também poderá ocorrer compartilhamento para cumprimento de obrigação legal, ordem judicial ou proteção de direitos.</p></> },
    { title: "Retenção e segurança", content: <><p>Os dados são mantidos pelo período necessário às finalidades informadas, às obrigações legais e ao exercício de direitos. Depois disso, poderão ser eliminados ou anonimizados, salvo hipótese legal de conservação.</p><p>São adotadas medidas técnicas e administrativas razoáveis para reduzir riscos de acesso indevido, perda, alteração ou divulgação. Nenhum ambiente digital, porém, é totalmente imune a incidentes.</p></> },
    { title: "Direitos do titular", content: <><p>O titular poderá solicitar confirmação de tratamento, acesso, correção, anonimização, bloqueio ou eliminação quando cabível, portabilidade, informação sobre compartilhamento, revogação do consentimento e revisão de decisões automatizadas, nos termos da LGPD.</p><p>Para proteger o próprio titular, poderá ser solicitada comprovação de identidade antes do atendimento. Se a solicitação não puder ser atendida, a justificativa será informada.</p></> },
    { title: "Transferências internacionais", content: <><p>Alguns provedores de tecnologia podem armazenar ou processar dados fora do Brasil. Nessas situações, buscamos fornecedores com mecanismos de proteção e condições compatíveis com a legislação aplicável.</p></> },
    { title: "Atualizações desta política", content: <><p>Esta política poderá ser atualizada para refletir mudanças legais, técnicas ou operacionais. A versão vigente será sempre identificada pela data de atualização publicada nesta página.</p><p>Consulte a <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/L13709compilado.htm" target="_blank" rel="noreferrer">LGPD em texto compilado</a> e as orientações da <a href="https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados-1/direito-dos-titulares" target="_blank" rel="noreferrer">Agência Nacional de Proteção de Dados</a>.</p></> },
  ]} />;
}
